# Configurações do Site
title: QuaseLivro
name: Daniel Natalizi
description: Informações e opiniões de qualidade
url: "https://daniel-natalizi.github.io"  # Troque pelo seu usuário
baseurl: "/quaselivro"       # Troque pelo nome do seu repositório

# Configuração do Tema
remote_theme: pages-themes/architect@v0.2.0

# Plugins (obrigatório para o tema funcionar)
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
#  - jekyll-seo-tag

# Configurações de Build
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Configuração de URLs (importante para o GitHub Pages)
permalink: /:categories/:title/

# Configuração para postagens
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:categories/:title/

# Collections (para posts)
collections:
  posts:
    output: true
    permalink: /:collection/:path/

# Configurações do Autor (opcional)
author:
  name: "Daniel Natalizi"
  bio: "Informações e opiniões"
  location: "Brasil"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:seu-email@example.com"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "www.linkedin.com/in/daniel-natalizi-76a381b9"

# Customização de aparência
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/daniel-natalizi"
